---
title: "csv-corrector"
author: "Beck Addison"
date: "4/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(reshape2)
```

```{r data-import}
csv_data <- read_csv("data/donortools-updated.csv")
recurring_data <- read_csv("data/recurring-info.csv")

name_table <- data.frame(
  first_name = c(
    "Brett and Annie",
    "Casey and Meg",
    "Daniel and Kristen",
    "Heather",
    "Kayla",
    "Kayla",
    "Maggie",
    "Philem",
    "Rachel",
    "Rob and Mauri",
    "Shelby",
    "Tracy",
    "Sarah",
    "Annie",
    "Jason",
    "Rachel",
    "Sarah",
    "Sarah",
    "Nate and Haley",
    "Tracey",
    "Amelia",
    "Rob and Pearl",
    "Angela"
  ),
  last_name = c(
    "Balsley",
    "Herring",
    "McDonald",
    "Wrench",
    "Miller",
    "Sumile",
    "Addison",
    "Andress",
    "Hill",
    "Moser",
    "Davis",
    "Frohlich",
    "Hindin",
    "Hindin",
    "Faircloth",
    "Gracy",
    "Quigg",
    "Santos",
    "Tew",
    "Frolich",
    "Klacik",
    "Hernandez",
    "Fontanelli"
  ),
  ID = c(
    "1020",
    "1001",
    "1013",
    "1026",
    "1017",
    "1024",
    "1019",
    "1023",
    "1021",
    "1010",
    "1022",
    "1009",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1009",
    "",
    "",
    ""
  )
)
```

```{r csv_data_functs}

split_donation <- function(df) {
  df <- df %>%
    separate(
      col = "Splits",
      into = c("AMOUNT1","AMOUNT2"),
      sep = " and "
    )
  df <- df %>%
    separate(
      col = "AMOUNT1",
      into = c("AMOUNT1", "GIFT_NARRATIVE1"),
      sep = " for "
    )
  df <- df %>%
    separate(
      col = "AMOUNT2",
      into = c("AMOUNT2", "GIFT_NARRATIVE2"),
      sep = " for "
    )

   df$AMOUNT1 <- as.numeric(gsub('\\$', '', df$AMOUNT1))
   df$AMOUNT2 <- as.numeric(gsub('\\$','', df$AMOUNT2))
   df <- df %>%
     pivot_longer(
       cols = c(AMOUNT1, AMOUNT2),
       names_to = "AMOUNT_TYPE",
       values_to = "AMOUNT"
     )

   df <- df %>%
     mutate(
       GIFT_NARRATIVE = case_when(
         (AMOUNT_TYPE == "AMOUNT2") ~ GIFT_NARRATIVE2,
         (AMOUNT_TYPE == "AMOUNT1") ~ GIFT_NARRATIVE1,
         TRUE ~ NA_character_
       ),
     ) %>%
     select(
       -GIFT_NARRATIVE1,
       -GIFT_NARRATIVE2,
       -AMOUNT_TYPE,
     ) %>%
     filter(!is.na(AMOUNT))
      
   
  return(df)
}

code_items <- function(df) {
  df <- df %>%
    mutate(
      ORG_REC = case_when(
        (!is.na(`Company Name`))  ~ "Y",
        TRUE ~ "N"
      ),
      DONOR_TYPE = case_when(
        (!is.na(`Company Name`) && `Is Company?`) ~ "CO",
        (!is.na(`Company Name`) && !`Is Company?`) ~ "OR",
        TRUE ~ "IN"
      ),
      State = case_when(
        nchar(State) <= 2 ~ toupper(State),
        TRUE ~ State
      ),
      GIFT_DATE = as.Date(`Received Date`, "%d-%b-%y"),

      `Email Address` = tolower(`Email Address`),


    )
  
  df$`Phone Number` <- gsub("[^0-9]", "", df$`Phone Number`)
  
  return(df)
}

add_other_columns <- function(df) {
  df <- df %>%
    mutate(
      GSOLIC = NA_character_,
      checked = FALSE
      )
  
  first_vec <- name_table$first_name
  last_vec <- name_table$last_name
  for (row in 1:nrow(df)) {
    if (!df[row,]$checked) {
      
      check_string = df[row,]$Memo
      
      for (row2 in 1:nrow(name_table)) {

        last_name_match = any(grepl(pattern = name_table[row2,]$last_name, x = check_string, ignore.case = T))
        if(is.na(last_name_match)) {last_name_match = F}
        first_name_match = any(grepl(pattern = name_table[row2,]$first_name, x = check_string, ignore.case = T))
        if(is.na(first_name_match)) {first_name_match = F}
        unique_first = (str_count(first_vec, name_table[row2,]$first_name) == 1)
        unique_last = (str_count(last_vec, name_table[row2,]$last_name) == 1)
        if (last_name_match && unique_first) {  #Case when there is a last name available, and we know the first name for this last name is unique
          df[row,]$checked = T
          df[row,]$GSOLIC = paste(name_table[row2,]$first_name, name_table[row2,]$last_name, sep = " ")
          df[row,]$GSOLIC = paste(df[row,]$GSOLIC, name_table[row2,]$ID, sep = " - ")
        } else if (last_name_match && first_name_match) { #Case when there is a last name available, but the first name wasn't unique for this person, so we have to see if it's included
          df[row,]$checked = T
          df[row,]$GSOLIC = paste(name_table[row2,]$first_name, name_table[row2,]$last_name, sep = " ")
          df[row,]$GSOLIC = paste(df[row,]$GSOLIC, name_table[row2,]$ID, sep = " - ")
        } else if (first_name_match && unique_last) { #Case when the last_name didn't match, so we have to check for first name, and the last name for this first name is unique
          df[row,]$checked = T
          df[row,]$GSOLIC = paste(name_table[row2,]$first_name, name_table[row2,]$last_name, sep = " ")
          df[row,]$GSOLIC = paste(df[row,]$GSOLIC, name_table[row2,]$ID, sep = " - ")
        }
      }
      gsub(x = df[row,]$GSOLIC, pattern = " nolast", replacement = "")
      gsub(x = df[row,]$GSOLIC, pattern = "nofirst ", replacement = "")
      gsub(x = df[row,]$GSOLIC, pattern = " - noindex", replacement = "")
    }
  }
  return(df)
}

```

```{r initial-data-cleansing}
csv_data2 <- csv_data %>%
  mutate(
    ORG_REC = case_when(
      (!is.na(`Company Name`))  ~ "Y",
      TRUE ~ "N"
    ),
    DONOR_TYPE = case_when(
      (!is.na(`Company Name`) && `Is Company?`) ~ "CO",
      (!is.na(`Company Name`) && !`Is Company?`) ~ "OR",
      TRUE ~ "IN"
    ),
    TITLE <- Prefix,
    FIRST_NAME = `First Name`,
    LAST_NAMe = case_when(
      (!is.na(`Company Name`)) ~ `Company Name`,
      TRUE ~ `Last Name`
    ),
    OPT_LINE = `Other Names`,
    SPOUSE = case_when(
      (is.na(`Company Name`)) ~ `Other Names`,
      TRUE ~ NA_character_
    ),
    SALUTATION = `Recognition Name`,
    ADDRESS = `Address Line 1`,
    ADDRESS2 = `Address Line 2`,
    CITY = City,
    STATE = State,
    ZIP = Postal,
    COUNTRY = `Country`,
    ADDRESS_TYPE = case_when(
      (is.na(`Company Name`)) ~ "HOME",
      TRUE ~ "WORK"
    ),
    PHONE = gsub(
      pattern = "[ \\(\\)-]",
      replacement = "",
      x = `Phone Number`
    ),
    EMAIL = tolower(`Email Address`),
    GIFT_DATE = as.Date(`Received Date`, "%d-%b-%y"),
    AMOUNT = Amount,
    REF = `Check Number`,
    GIFT_TYPE = case_when(
      `Donation Type` == "Check" ~ "CH",
      `Donation Type` == "PayPal" ~ "PP",
      `Donation Type` == "Online Donation" ~ "ON",
      `Donation Type` == "One time General Donation" ~ "CC",
      `Donation Type` == "Monthly General Donation" && is.na(`Check Number`) ~ "ACH",
      TRUE ~ "CA",
    ),
    GL_CODE = NA_character_,
    GSOLIC = NA_character_,
    PLEDGE_PAYMENT = NA_character_,
    GIFT_NARRATIVE = Memo
  )

for(i in 1:nrow(csv_data2)) {
  row = csv_data2[i,]
  if (grepl("SPONSORSHIP", x = row$Memo, ignore.case = T)) {
    csv_data2[i,]$GL_CODE = "SPONSORSHIP"
  } else {
    csv_data2[i,]$GL_CODE = "UN"
  }
  
  if (grepl("paid in full", x = row$Memo, ignore.case = T)) {
    csv_data2[i,]$PLEDGE_PAYMENT = "N"
  } else if (any(grepl("Monthly|Bridge Way|Sponsorship", x = row$Memo, ignore.case = T))) {
    csv_data2[i,]$PLEDGE_PAYMENT = "Y"
  } else if (any(grepl("JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC", x = row$Memo, ignore.case = T))) {
    csv_data2[i,]$PLEDGE_PAYMENT = "Y"
  } else {
    csv_data2[i,]$PLEDGE_PAYMENT = "N"
  }
}

for (j in 1:nrow(csv_data2)){
  memo = csv_data2[j,]$Memo
  for (i in 1:nrow(name_table)) {
    
    first = name_table[i,]$first_name
    last = name_table[i,]$last_name
    id = name_table[i,]$ID
    
    if (any(grepl(pattern = first, x = memo, ignore.case = T)) && any(grepl(pattern = last, x = memo, ignore.case = T))) {
      csv_data2[j,]$GSOLIC = paste(paste(first,last, sep = " "), id, sep = " - ")
    } else if (any(grepl(pattern = first, x = memo, ignore.case = T)) && !any(grepl(pattern = last, x = memo, ignore.case = T))) {
      if (nrow(name_table[grepl(pattern = last, x = name_table$last_name, ignore.case = T),]) == 1) {
        csv_data2[j,]$GSOLIC = paste(paste(first,last, sep = " "), id, sep = " - ")
      } else {
        csv_data2[j,]$GSOLIC = first
      }
    } else if (!any(grepl(pattern = first, x = memo, ignore.case = T)) && any(grepl(pattern = last, x = memo, ignore.case = T))) {
      if (nrow(name_table[grepl(pattern = first, x = name_table$first_name, ignore.case = T),])) {
        csv_data2[j,]$GSOLIC = paste(paste(first,last, sep = " "), id, sep = " - ")
      } else {
        csv_data2[j,]$GSOLIC = last
      }
    }
  }
}

```


```{r select}
final_export <- csv_data_flat %>%
  select(
    ORG_REC,
    DONOR_TYPE,
    TITLE,
    FIRST_NAME,
    LAST_NAME,
    OPT_LINE,
    SPOUSE,
    SALUTATION,
    ADDRESS,
    ADDRESS2,
    CITY,
    STATE,
    ZIP,
    ADDRESS_TYPE,
    MOBILE_PHONE,
    BUSINESS_PHONE,
    HOME_PHONE,
    EMAIL,
    GIFT_DATE,
    AMOUNT,
    GL_CODE,
    GSOLIC,
    PLEDGE_PAYMENT,
    REF,
    GIFT_TYPE,
    GIFT_NARRATIVE
  )
```

```{r export}
unlink("data/final.csv")
write.csv(
  x = final_export,
  file = "data/final.csv",
  na = "",
  )
```
